import { FormEvent } from "react";
import { AnimatePresence, motion } from "motion/react";
import { X } from "lucide-react";
import { MoodEntry } from "../types";

interface MoodModalProps { open: boolean; mood: MoodEntry["mood"]; note: string; onMoodChange: (value: MoodEntry["mood"]) => void; onNoteChange: (value: string) => void; onSubmit: (e: FormEvent) => void; onClose: () => void; }
const moods = [{ id: "xursand", label: "Xursand", emoji: "😊" }, { id: "yaxshi", label: "Yaxshi", emoji: "🙂" }, { id: "normal", label: "Oddiy", emoji: "😐" }, { id: "charchagan", label: "Charchagan", emoji: "😫" }, { id: "yomon", label: "Xafa", emoji: "😢" }, { id: "havotirli", label: "Xavotir", emoji: "😰" }, { id: "g'azabli", label: "Asabiy", emoji: "😡" }] as const;
export default function MoodModal({ open, mood, note, onMoodChange, onNoteChange, onSubmit, onClose }: MoodModalProps) {
  return <AnimatePresence>{open && <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm flex items-center justify-center p-4 z-50"><motion.div initial={{ scale: .95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: .95, opacity: 0 }} className="bg-white rounded-3xl max-w-md w-full p-6 md:p-8 shadow-2xl border border-sky-100" id="add-mood-modal"><div className="flex justify-between items-center mb-4 pb-2 border-b border-sky-100"><h3 className="text-base font-black text-indigo-900 uppercase tracking-wide">Kunlik kayfiyatingizni yozing</h3><button onClick={onClose} className="p-1.5 hover:bg-sky-100 rounded-lg transition-colors text-slate-400" aria-label="Modalni yopish"><X size={18} /></button></div><form onSubmit={onSubmit} className="flex flex-col gap-4"><div><label className="text-xs font-bold text-slate-500 block mb-2">Hozirgi holatingiz</label><div className="grid grid-cols-4 gap-2">{moods.map((m) => <button key={m.id} type="button" onClick={() => onMoodChange(m.id)} className={`p-2 rounded-xl border flex flex-col items-center justify-center gap-1 transition-all ${mood === m.id ? "bg-indigo-50 border-indigo-400 text-indigo-700 font-extrabold" : "bg-stone-50 border-stone-200 text-slate-500 hover:bg-stone-100"}`}><span className="text-xl select-none">{m.emoji}</span><span className="text-[10px] font-bold">{m.label}</span></button>)}</div></div><div><label className="text-xs font-bold text-slate-500 block mb-1">Nimalar sodir bo'ldi (eslatma)?</label><textarea required rows={3} value={note} onChange={(e) => onNoteChange(e.target.value)} placeholder="Masalan: Bugun imtihonni yaxshi topshirdim, kayfiyatim a'lo." className="w-full bg-slate-50 border-2 border-slate-100 rounded-2xl px-4 py-3 text-sm outline-none focus:border-indigo-400 focus:ring-2 focus:ring-indigo-100 text-slate-800 font-medium" id="manual-mood-note" /></div><button type="submit" className="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 rounded-2xl text-sm transition-all shadow-md">Kundalikka qo'shish</button></form></motion.div></div>}</AnimatePresence>;
}
